language: node_js
node_js:
  - 10

install:
  - yarn add -D vue@next
  - yarn install

script:
  - yarn docs

deploy:
  provider: pages
  local_dir: docs
  on:
    branch: master
  token: $GITHUB_TOKEN
  skip_cleanup: true
  keep_history: true
  committer_from_gh: true